name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          TEST_ERRORS=$(npm test) || echo "Testfehler gefunden."
          LINT_ERRORS=$(npm run lint) || echo "Linting-Fehler gefunden."
          echo "TEST_ERRORS=$TEST_ERRORS" >> $GITHUB_ENV
          echo "LINT_ERRORS=$LINT_ERRORS" >> $GITHUB_ENV

      - name: Send message to Zulip
        env:
          ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
          ZULIP_CHANNEL: ${{ secrets.ZULIP_CHANNEL }}
          ZULIP_BOT_EMAIL: ${{ secrets.ZULIP_BOT_EMAIL }}
        run: |
          TEST_ERRORS="${{ env.TEST_ERRORS }}"
          LINT_ERRORS="${{ env.LINT_ERRORS }}"
          MESSAGE="Testfehler:\n$TEST_ERRORS\nLinting-Fehler:\n$LINT_ERRORS"

          if [ "$TEST_ERRORS" != "Keine Fehler gefunden" ] || [ "$LINT_ERRORS" != "Keine Fehler gefunden" ]; then
            curl -X POST -H 'Content-Type: application/json' \
            --data "{\"type\": \"stream\", \"to\": \"$ZULIP_CHANNEL\", \"topic\": \"CI Status\", \"content\": \"$MESSAGE\"}" \
            -u "$ZULIP_BOT_EMAIL:$ZULIP_API_KEY" \
            https://ihkprojekt.zulipchat.com/api/v1/send_message || echo "Failed to send message"
          else
            MESSAGE="Tests erfolgreich oder keine Fehler gefunden."
            curl -X POST -H 'Content-Type: application/json' \
            --data "{\"type\": \"stream\", \"to\": \"$ZULIP_CHANNEL\", \"topic\": \"CI Status\", \"content\": \"$MESSAGE\"}" \
            -u "$ZULIP_BOT_EMAIL:$ZULIP_API_KEY" \
            https://ihkprojekt.zulipchat.com/api/v1/send_message || echo "Failed to send message"
          fi
