name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          npm test > test_output.log || true
          echo "TEST_RESULT=$(grep -E 'FAIL|ERROR' test_output.log || echo 'Keine Fehler gefunden')" >> $GITHUB_ENV

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: |
          npm run lint > lint_output.log || true
          echo "LINT_RESULT=$(grep 'error' lint_output.log || echo 'Keine Fehler gefunden')" >> $GITHUB_ENV

  notify:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Send message to Zulip
        env:
          ZULIP_BOT_EMAIL: ${{ secrets.ZULIP_BOT_EMAIL }}
          ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
          ZULIP_CHANNEL: ${{ secrets.ZULIP_CHANNEL }}
          TEST_ERRORS: ${{ env.TEST_RESULT }}
          LINT_ERRORS: ${{ env.LINT_RESULT }}
        run: |
          echo "TEST_ERRORS: $TEST_ERRORS"
          echo "LINT_ERRORS: $LINT_ERRORS"

          if [ "$TEST_ERRORS" != "Keine Fehler gefunden" ] || [ "$LINT_ERRORS" != "Keine Fehler gefunden" ]; then
            MESSAGE="Testfehler:\n$TEST_ERRORS\n\nLinting-Fehler:\n$LINT_ERRORS"
            echo "Sending error message..."
          else
            MESSAGE="Alle Tests und der Linter sind erfolgreich durchgelaufen."
            echo "Sending success message..."
          fi
          
          curl -X POST -u "${ZULIP_BOT_EMAIL}:${ZULIP_API_KEY}" \
            -d "type=stream" \
            -d "to=${ZULIP_CHANNEL}" \
            -d "subject=CI Status" \
            -d "content=$MESSAGE" \
            https://ihkprojekt.zulipchat.com/api/v1/messages
